CREATE TABLE [dbo].[Category]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(500) NOT NULL,
	[Order] INT NOT NULL,
	[Image] VARBINARY(MAX) NOT NULL,	
	[CreateDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[ModifiedDate] DATETIME NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0
)
