CREATE TABLE [dbo].[Client]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserName] VARCHAR(250) NOT NULL,
	[Password] VARCHAR(1000) NOT NULL,
	[CreatedDate] DATETIME NOT NULL DEFAULT GETDATE()
)
