CREATE TABLE [dbo].[User]
(
	[Id]			INT				NOT NULL	PRIMARY KEY,
	[Username]		VARCHAR(500)	NOT NULL,
	[Password]		VARCHAR(1000)	NOT NULL,
	[FullName]		VARCHAR(500)	NOT NULL,
	[Email]			VARCHAR(500)	NOT NULL,
	[IsActive]		BIT				NOT NULL	DEFAULT		0,
	[UserType]		VARCHAR(25)		NOT NULL	DEFAULT		'Standard',
	[CreatedDate]	DATETIME		NOT NULL	DEFAULT		GETDATE(),
	[CreatedBy]		VARCHAR(500)	NOT NULL,
	[ModifiedDate]	DATETIME		NULL,
	[ModifiedBy]	VARCHAR(500)	NULL,
	[IsDeleted]		BIT				NOT NULL	DEFAULT		0
)
